version: '3'
services:

  kafka:
      image: bitnami/kafka:latest
      ports:
        - "9092:9092"
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper

  zookeeper:
      image: bitnami/zookeeper:latest
      ports:
        - "2181:2181"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes


  ml_model:
      build:
        context: .
        dockerfile: Dockerfile.ml_model
      depends_on:
        - consumer

  consumer:
      build:
        context: .
        dockerfile: Dockerfile.consumer
      depends_on:
        - kafka
        
