version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./server.properties:/etc/kafka/server.properties