apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
  namespace: team13
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - '["ReadWriteOnce"]' #error here 
  hostPath:
    path: "/kubedata/" 