apiVersion: batch/v1
kind: Job
metadata:
  name: test2-job
  namespace: team13
  labels:
    app: test2-job
spec:
  template:
    metadata:
      name: test2-job
      labels:
        app: test2-job
    spec:
      volumes:
      - name: test2-pv-storage
        persistentVolumeClaim:
          claimName: test2-pvc
      containers:
      - name: test2-job
        image: 192.168.1.64:5000/testvolume
        command: ['python', 'test.py']        
        volumeMounts:
        - name: test2-pv-storage
          mountPath: "./data"
      
      restartPolicy: Never
      dnsPolicy: ClusterFirst