apiVersion: v1
kind: PersistentVolume
metadata:
  name: test2-volume
  namespace: team13
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - "ReadWriteOnce" #write this as a string
  hostPath:
    path: "/kubedata" 