apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: team13
  labels:
    app: test-pvc
spec:
  storageClassName: manual #make sure that storage maches the test-volume storage
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
