apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: team13
  labels:
    app: test-job
spec:
  template:
    metadata:
      name: test-job
      labels:
        app: test-job
    spec:
      volumes:
      - name: test-pv-storage
        persistentVolumeClaim:
          claimName: test-pvc
      containers:
      - name: test-job
        image: 192.168.1.64:5000/testvolume
        command: ['python', 'test.py']        
        volumeMounts:
        - name: test-pv-storage
          mountPath: "/data/"