FROM apache/kafka


# Expose Kafka broker port
EXPOSE 9092

# Set environment variables for Kafka to work with Zookeeper
# ENV KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
# ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
# ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

# # Start Kafka server
# CMD ["/etc/confluent/docker/run"]